export const basicComponents = [
  {
    type: 'input',
    name: '单行文本',
    labelWidth: '',
    hidden: false,
    icon: 'regular/keyboard',
    options: {
      width: '100%',
      defaultValue: '',
      readonly: false,
      disabled: false,
      showWordLimit: false,
      required: false,
      dataType: 'string',
      pattern: '',
      maxLength: '',
      placeholder: '',
      hiddenLabel: false,
      appendButton: false, // 后缀功能按钮
    },
  },
  {
    type: 'textarea',
    name: '多行文本',
    icon: 'regular/keyboard',
    labelWidth: '',
    hidden: false,
    options: {
      width: '100%',
      defaultValue: '',
      readonly: false,
      disabled: false,
      showWordLimit: false,
      required: false,
      maxLength: '',
      pattern: '',
      placeholder: '',
      hiddenLabel: false,
    },
  },
  {
    type: 'number',
    name: '计数器',
    icon: 'sort-numeric-up',
    labelWidth: '',
    hidden: false,
    options: {
      width: '',
      required: false,
      defaultValue: 0,
      min: '',
      max: '',
      step: 1,
      disabled: false,
      controlsPosition: '',
      hiddenLabel: false,
    },
  },
  {
    type: 'radio',
    name: '单选框组',
    icon: 'regular/dot-circle',
    labelWidth: '',
    hidden: false,
    options: {
      inline: true,
      defaultValue: '',
      showLabel: false,
      hiddenLabel: false,
      options: [
        {
          value: '选项1',
          label: '选项1',
        },
        {
          value: '选项2',
          label: '选项2',
        },
        {
          value: '选项3',
          label: '选项3',
        },
      ],
      required: false,
      disabled: false,
      width: '',
      remote: 'static',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
    },
  },
  {
    type: 'checkbox',
    name: '多选框组',
    icon: 'regular/check-square',
    labelWidth: '',
    hidden: false,
    options: {
      inline: true,
      buttonStyle: false,
      defaultValue: [],
      showLabel: false,
      disabled: false,
      min: null,
      max: null,
      hiddenLabel: false,
      options: [
        {
          value: '选项1',
        },
        {
          value: '选项2',
        },
        {
          value: '选项3',
        },
      ],
      required: false,
      width: '',
      remote: false,
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
    },
  },
  {
    type: 'date',
    name: '日期选择器',
    labelWidth: '',
    hidden: false,
    icon: 'regular/calendar-alt',
    options: {
      hiddenLabel: false,
      defaultValue: false,
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      type: 'date',
      format: 'yyyy-MM-dd',
      timestamp: false,
      required: false,
      width: '100%',
    },
  },
  {
    type: 'date',
    name: '时间选择器',
    labelWidth: '',
    hidden: false,
    icon: 'clock',
    options: {
      hiddenLabel: false,
      defaultValue: '',
      readonly: false,
      disabled: false,
      editable: true,
      clearable: true,
      placeholder: '',
      startPlaceholder: '',
      endPlaceholder: '',
      type: 'datetime',
      format: 'yyyy-MM-dd hh:mm:ss',
      timestamp: false,
      required: false,
      width: '100%',
    },
  },
  {
    type: 'rate',
    name: '评分',
    icon: 'regular/star',
    labelWidth: '',
    hidden: false,
    options: {
      hiddenLabel: false,
      defaultValue: null,
      max: 5,
      disabled: false,
      allowHalf: false,
      required: false,
    },
  },
  {
    type: 'color',
    name: '颜色选择器',
    icon: 'palette',
    labelWidth: '',
    hidden: false,
    options: {
      hiddenLabel: false,
      defaultValue: '',
      disabled: false,
      showAlpha: false,
      required: false,
    },
  },
  {
    type: 'select',
    name: '下拉选择框',
    labelWidth: '',
    hidden: false,
    icon: 'regular/caret-square-down',
    options: {
      hiddenLabel: false,
      defaultValue: '',
      multiple: false,
      disabled: false,
      clearable: false,
      placeholder: '',
      required: false,
      showLabel: false,
      allowCreate: false,
      width: '100%',
      options: [
        {
          value: '下拉框1',
        },
        {
          value: '下拉框2',
        },
        {
          value: '下拉框3',
        },
      ],
      remote: 'static',
      remoteOptions: [],
      props: {
        value: 'value',
        label: 'label',
      },
      remoteFunc: '',
    },
  },
  {
    type: 'switch',
    name: '开关',
    labelWidth: '',
    hidden: false,
    icon: 'toggle-off',
    options: {
      hiddenLabel: false,
      defaultValue: false,
      required: false,
      disabled: false,
    },
  },
  {
    type: 'slider',
    name: '滑块',
    icon: 'sliders-h',
    labelWidth: '',
    hidden: false,
    options: {
      hiddenLabel: false,
      defaultValue: 0,
      disabled: false,
      required: false,
      min: 0,
      max: 100,
      step: 1,
      showInput: false,
      range: false,
      width: '',
    },
  },
  {
    type: 'button',
    name: '按钮',
    icon: 'mouse-pointer',
    labelWidth: '',
    hidden: false,
    options: {
      text: '确认',
      eventName: 'btnCallback',
      hiddenLabel: true,
    },
  },
  {
    type: 'text',
    name: '文本',
    icon: 'language',
    options: {
      defaultValue: '',
      remoteFunc: '',
      align: 'center',
      fontSize: '16px',
      hiddenLabel: false,
    },
  },
  {
    type: 'html',
    name: 'HTML',
    icon: 'heading',
    labelWidth: '',
    options: {
      html: null,
      hiddenLabel: false,
    },
  },
];

export const advanceComponents = [
  {
    type: 'blank',
    name: '自定义(插槽)',
    icon: 'chalkboard',
    labelWidth: '',
    options: {
      defaultType: 'String',
      hiddenLabel: false,
    },
  },
  {
    type: 'upload',
    name: '附件',
    icon: 'upload',
    labelWidth: '',
    options: {
      resourceId: 'id',
      fileType: '',
      defaultValue: '',
      remoteFunc: '',
      readonly: false,
      hiddenLabel: false,
    },
  },
  {
    type: 'avatar',
    name: '头像',
    icon: 'user',
    labelWidth: '',
    options: {
      resourceId: 'id',
      uploadUrl: '/file/upload',
      width: '180px',
      hiddenLabel: true,
    },
  },
  {
    type: 'cascader',
    name: '级联选择器',
    icon: 'random',
    labelWidth: '',
    options: {
      defaultValue: [],
      width: '100%',
      separator: '/',
      placeholder: '',
      multiple: false,
      disabled: false,
      clearable: false,
      checkStrictly: false,
      remote: 'static',
      remoteOptions: [],
      options: [],
      props: {
        value: 'value',
        label: 'label',
        children: 'children',
      },
      remoteFunc: '',
      hiddenLabel: false,
    },
  },
  {
    type: 'table',
    name: '子表格',
    icon: 'table',
    labelWidth: '',
    options: {
      remoteFunc: '',
      visibleList: {
        actionColumnBtnEdit: true,
        actionColumnBtnDetail: false,
        btnAdd: true,
        actionColumn: true,
        tableTitle: false,
        searchForm: false,
        actionColumnBtnDel: true,
      },
      tableParams: '',
      prefill: '',
      tableTitle: '',
      showPagination: true,
      isMultiple: false,
      tableName: '',
      tableDesignerName: '',
      dialogFormDesignerName: '',
      hiddenLabel: false,
    },
  },
  {
    type: 'form',
    name: '子表单',
    icon: 'file-word',
    labelWidth: '',
    tableColumns: [],
    options: {
      hiddenLabel: true,
      remote: 'custom',
      remoteFunc: '',
      tableParams: '',
      prefill: '',
      tableName: '',
    },
  },
  // 目前暂时提供了几个常用props,有更多需要自行拓展
  // 官网:https://vue-treeselect.js.org
  {
    type: 'treeselect',
    name: '树形下拉框',
    icon: 'tree',
    labelWidth: '',
    options: {
      remoteFunc: '',
      placeholder: '',
      width: '100%',
      maxHeight: 300,
      multiple: false,
      remote: 'custom',
      appendToBody: false,
      props: {
        value: 'value',
        label: 'label',
        children: 'children',
      },
      clearable: true,
      searchable: true,
      noChildrenText: '暂无数据',
      noOptionsText: '暂无数据',
      noResultsText: '暂无数据',
      searchNested: true,
      required: false,
      showValueLabelSlot: false,
      disabled: false,
      showCount: false,
      disableBranchNodes: true,
      remoteOptions: [],
      hiddenLabel: false,
    },
  },
  {
    type: 'richtext',
    name: '富文本',
    icon: 'text-width',
    labelWidth: '',
    hidden: false,
    options: {
      defaultValue: '',
      readonly: false,
      hiddenLabel: false,
    },
  },
];

export const layoutComponents = [
  {
    type: 'grid',
    name: '栅格布局',
    icon: 'th',
    columns: [
      {
        span: 24,
        list: [],
      },
    ],
    options: {
      gutter: 0,
      justify: 'start',
      align: 'top',
    },
  },
  {
    type: 'tabs',
    name: '标签页',
    icon: 'tags',
    items: [
      {
        name: '标签页1',
        label: '标签页1',
        list: [],
      },
    ],
    options: {
      type: '',
      hiddenLabel: true,
      tabPosition: 'top',
    },
  },
  {
    type: 'divider',
    name: '分割线',
    icon: 'divide',
    labelWidth: '',
    options: {
      align: 'center',
      hiddenLabel: true,
    },
  },
];

export const chartComponents = [
  {
    type: 'chart-pie',
    name: '饼图',
    icon: 'chart-pie',
    options: {
      className: '',
      width: '100%',
      // title: '饼图',
      option: '',
      hiddenLabel: true,
      hollow: true,
      height: '300px',
      data: [
        {
          name: '商品一',
          value: '20',
        },
        {
          name: '商品二',
          value: '5',
        },
        {
          name: '商品三',
          value: '10',
        },
      ],
    },
  },
  {
    type: 'chart-line',
    name: '柱状/折线图',
    icon: 'chart-line',
    options: {
      className: '',
      yAxisMax: null,
      width: '100%',
      type: 'bar',
      // title: '饼图',
      option: '',
      rotate: false, // x,y轴互换
      xUnit: '', // x轴单位
      yUnit: '个', // y轴单位
      hiddenLabel: true,
      height: '400px',
      data: [
        {
          name: '商品一',
          value: '20',
        },
        {
          name: '商品二',
          value: '5',
        },
        {
          name: '商品三',
          value: '10',
        },
      ],
    },
  },
  {
    type: 'chart-common',
    name: '通用图表',
    icon: 'chart-bar',

    options: {
      className: '',
      height: '400px',
      hiddenLabel: true,
      width: '100%',
      loop: false,
      option: {
        xAxis: {
          type: 'category',
          data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        },
        yAxis: {
          type: 'value',
        },
        series: [{
          data: [150, 230, 224, 218, 135, 147, 260],
          type: 'line',
        }],
      },
    },
  },
];


// 组件配置信息枚举
export const elementComponentConfig = {
  tabs: {
    type: [{ label: '普通', value: '' }, { label: '选项卡', value: 'card' }, { label: '卡片化', value: 'border-card' }],
    position: [{ label: '顶部', value: 'top' }, { label: '左侧', value: 'left' }, { label: '右侧', value: 'right' }, { label: '底部', value: 'bottom' }],
  },
};
